### ISSUE TITLE
Repo can't be compiled using the latest version optimizer

### ISSUE THREAD

**Issue by fuzious** [baedrik/snip721-reference-impl#20]
![image](https://user-images.githubusercontent.com/42795731/229339352-a8f72349-ae61-49bd-835e-4424d56a5656.png)

Although it is compilable using the version 1.0.10

**Comment by baedrik** [comment]
Hmm...I just tried and it worked:

docker run -v /mnt/c/Projects/testdocker:/contract enigmampc/secret-contract-optimizer:latest
    Updating git repository `https://github.com/scrtlabs/cosmwasm`
    Updating crates.io index
    Updating git repository `https://github.com/scrtlabs/secret-toolkit`
 Downloading crates ...
  Downloaded rand_chacha v0.3.1
  Downloaded ryu v1.0.13
  Downloaded quote v1.0.23
  Downloaded base64 v0.13.1
  Downloaded opaque-debug v0.3.0
  Downloaded rfc6979 v0.3.1
  Downloaded subtle v2.4.1
  Downloaded block-buffer v0.10.4
  Downloaded block-buffer v0.9.0
  Downloaded itoa v1.0.6
  Downloaded fixed-hash v0.8.0
  Downloaded cfg-if v1.0.0
  Downloaded dyn-clone v1.0.11
  Downloaded bech32 v0.9.1
  Downloaded crunchy v0.2.2
  Downloaded base16ct v0.1.1
  Downloaded primitive-types v0.12.1
  Downloaded version_check v0.9.4
  Downloaded ff v0.12.1
  Downloaded ppv-lite86 v0.2.17
  Downloaded sha2 v0.9.9
  Downloaded thiserror v1.0.39
  Downloaded rand_core v0.6.4
  Downloaded sha2 v0.10.6
  Downloaded schemars_derive v0.8.12
  Downloaded getrandom v0.2.8
  Downloaded forward_ref v1.0.0
  Downloaded static_assertions v1.1.0
  Downloaded cpufeatures v0.2.5
  Downloaded digest v0.9.0
  Downloaded remain v0.2.7
  Downloaded generic-array v0.14.6
  Downloaded base64ct v1.6.0
  Downloaded hex v0.4.3
  Downloaded group v0.12.1
  Downloaded serde_derive_internals v0.26.0
  Downloaded signature v1.6.4
  Downloaded serde-json-wasm v0.4.1
  Downloaded byteorder v1.4.3
  Downloaded ed25519-zebra v3.1.0
  Downloaded bincode2 v2.0.1
  Downloaded ripemd v0.1.3
  Downloaded thiserror-impl v1.0.39
  Downloaded sec1 v0.3.0
  Downloaded pkcs8 v0.9.0
  Downloaded uint v0.9.5
  Downloaded digest v0.10.6
  Downloaded ecdsa v0.14.8
  Downloaded rand_core v0.5.1
  Downloaded const-oid v0.9.2
  Downloaded proc-macro2 v1.0.51
  Downloaded crypto-common v0.1.6
  Downloaded spki v0.6.0
  Downloaded ahash v0.7.6
  Downloaded once_cell v1.17.1
  Downloaded unicode-ident v1.0.8
  Downloaded elliptic-curve v0.12.3
  Downloaded zeroize v1.5.7
  Downloaded schemars v0.8.12
  Downloaded crypto-bigint v0.4.9
  Downloaded typenum v1.16.0
  Downloaded serde_derive v1.0.154
  Downloaded hmac v0.12.1
  Downloaded derivative v2.2.0
  Downloaded serde v1.0.154
  Downloaded base64 v0.21.0
  Downloaded k256 v0.11.6
  Downloaded hashbrown v0.12.3
  Downloaded der v0.6.1
  Downloaded serde_json v1.0.94
  Downloaded syn v1.0.109
  Downloaded curve25519-dalek v3.2.0
  Downloaded libc v0.2.140
   Compiling proc-macro2 v1.0.51
   Compiling unicode-ident v1.0.8
   Compiling quote v1.0.23
   Compiling syn v1.0.109
   Compiling serde_derive v1.0.154
   Compiling serde v1.0.154
   Compiling crunchy v0.2.2
   Compiling byteorder v1.4.3
   Compiling static_assertions v1.1.0
   Compiling version_check v0.9.4
   Compiling typenum v1.16.0
   Compiling serde_json v1.0.94
   Compiling ryu v1.0.13
   Compiling itoa v1.0.6
   Compiling thiserror v1.0.39
   Compiling hex v0.4.3
   Compiling schemars v0.8.12
   Compiling dyn-clone v1.0.11
   Compiling base64 v0.13.1
   Compiling forward_ref v1.0.0
   Compiling rand_core v0.6.4
   Compiling ppv-lite86 v0.2.17
   Compiling cfg-if v1.0.0
   Compiling bech32 v0.9.1
   Compiling generic-array v0.14.6
   Compiling subtle v2.4.1
   Compiling fixed-hash v0.8.0
   Compiling rand_chacha v0.3.1
   Compiling base64 v0.21.0
   Compiling uint v0.9.5
   Compiling primitive-types v0.12.1
   Compiling serde_derive_internals v0.26.0
   Compiling thiserror-impl v1.0.39
   Compiling cosmwasm-derive v1.1.9 (https://github.com/scrtlabs/cosmwasm?tag=v1.1.9-secret#e40a15f0)
   Compiling derivative v2.2.0
   Compiling remain v0.2.7
   Compiling schemars_derive v0.8.12
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling digest v0.10.6
   Compiling sha2 v0.10.6
   Compiling ripemd v0.1.3
   Compiling serde-json-wasm v0.4.1
   Compiling bincode2 v2.0.1
   Compiling cosmwasm-std v1.1.9 (https://github.com/scrtlabs/cosmwasm?tag=v1.1.9-secret#e40a15f0)
   Compiling cosmwasm-storage v1.1.9 (https://github.com/scrtlabs/cosmwasm?tag=v1.1.9-secret#e40a15f0)
   Compiling secret-toolkit-crypto v0.8.0 (https://github.com/scrtlabs/secret-toolkit?tag=v0.8.0#dfbcc26e)
   Compiling secret-toolkit-serialization v0.8.0 (https://github.com/scrtlabs/secret-toolkit?tag=v0.8.0#dfbcc26e)
   Compiling secret-toolkit-utils v0.8.0 (https://github.com/scrtlabs/secret-toolkit?tag=v0.8.0#dfbcc26e)
   Compiling secret-toolkit-permit v0.8.0 (https://github.com/scrtlabs/secret-toolkit?tag=v0.8.0#dfbcc26e)
   Compiling secret-toolkit-storage v0.8.0 (https://github.com/scrtlabs/secret-toolkit?tag=v0.8.0#dfbcc26e)
   Compiling secret-toolkit-viewing-key v0.8.0 (https://github.com/scrtlabs/secret-toolkit?tag=v0.8.0#dfbcc26e)
   Compiling secret-toolkit v0.8.0 (https://github.com/scrtlabs/secret-toolkit?tag=v0.8.0#dfbcc26e)
   Compiling snip721-reference-impl v1.0.0 (/contract)
    Finished release [optimized] target(s) in 3m 18s

**Comment by fuzious** [comment]
Weird, also are u able to upload it to pulsar testnet? I try to but it gets timed out , I try with my other contracts using this script and successfully retrieve `Code ID`  . Any thoughts on this please? 
I compiled and uploaded it using
```
docker run --rm -v "$(pwd)":/contract   --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target   --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry   enigmampc/secret-contract-optimizer:1.0.10
```
```
const wallet = new Wallet('');
    const txEncryptionSeed = EncryptionUtilsImpl.GenerateNewSeed();
    const secretjs = new SecretNetworkClient({
        chainId: "pulsar-2",
        url: "http://testnet.securesecrets.org:1317",
        wallet: wallet,
        walletAddress: wallet.address,
    });
    console.log(`Wallet address=${wallet.address}`);
    const accAddress = wallet.address;

    const wasm = fs.readFileSync("snip721-reference-impl/contract.wasm.gz");
    console.log("Uploading contract");

    let tx = await secretjs.tx.compute.storeCode(
        {
            sender: wallet.address,
            wasm_byte_code: wasm,
            source: "",
            builder: "",
        },
        {
            gasLimit: 100_000_000,
        }
    );

    console.log(tx);
```

**Comment by fuzious** [comment]
Closing this since I was successfully able to upload it using secretcli but still can't do it using secretjs
