### ISSUE TITLE
I think this should be secret-3 instead

### ISSUE THREAD

**Issue by alejandrordzl** [baedrik/snip721-reference-impl#3]
https://github.com/baedrik/snip721-reference-impl/blob/731a5a5023618fff71b76c3eef74c7a501114f0c/src/contract.rs#L2443

I know it's in case cannot read information for the blockchain but I think may cause some probles since secret-2 is deprecated

**Comment by alejandrordzl** [comment]
I just referenced one `chain_id` but there are many others, maybe have them all over a single constant variable ?

**Comment by baedrik** [comment]
It doesn't cause any problems because the chain-id field is never looked at.  But that said, if I remember, I might change it when I do the next updates just to ease reader's minds if they see it

**Comment by baedrik** [comment]
might even change it to:
```rust
chain_id: "unused".to_string(),
```
so people are aware
