### ISSUE TITLE
Cannot run secret-contract-optimizer

### ISSUE THREAD

**Issue by pyr0gan** [baedrik/snip721-reference-impl#5]
### Issue

When attempting to run the [secret contract optimizer](https://hub.docker.com/r/enigmampc/secret-contract-optimizer) with this repo as part of [this Figment Learn tutorial](https://learn.figment.io/tutorials/deploy-your-own-secret-nft), it currently fails to build the `uint` crate with the following error:

```text
error: package `uint v0.9.3` cannot be built because it requires rustc 1.56.1 or newer, 
while the currently active rustc version is 1.56.0
make: *** [compile-optimized-reproducible] Error 101
```

This was brought to my attention by @MarkH1994 on the Figment Devs discord server. We were able to determine that version 0.9.0 of the `uint` crate works in this scenario because it doesn't require a higher `rustc` version than the Docker container has installed.

@baedrik Would it be preferable to try getting the contract optimizer Docker image updated to use a higher version of `rustc`? I just don't know who maintains it or I'd ask directly.

Thanks for your assistance! 😄

**Comment by baedrik** [comment]
One of the dependencies must have changed recently.  I think @assafmo maintains the optimizer

**Comment by baedrik** [comment]
It appears to be a dependency of the primitive-types crate.  If the optimizer isn't likely to be updated, I'll see if I can use a different crate

**Comment by luca992** [comment]
I'm also trying to follow the Deploy your own secret NFT tutorial and I'm having problems with the optimizer. I can't get primitive-types to compile. I get the error every time. I tried updating it to 0.11.1. But that did not help.

```
error: could not compile `primitive-types`

Caused by:
  process didn't exit successfully: `rustc --crate-name primitive_types --edition=2018 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.9.1/src/lib.rs 
--error-format=json --json=diagnostic-rendered-ansi,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort 
-C codegen-units=1 -C overflow-checks=on -C metadata=bcfdc8edbed858c9 -C extra-filename=-bcfdc8edbed858c9 
--out-dir /contract/target/wasm32-unknown-unknown/release/deps --target wasm32-unknown-unknown -L dependency=/contract/target/wasm32-unknown-unknown/release/deps 
-L dependency=/contract/target/release/deps --extern fixed_hash=/contract/target/wasm32-unknown-unknown/release/deps/libfixed_hash-ff3b73f0cbe8b61f.rmeta 
--extern uint=/contract/target/wasm32-unknown-unknown/release/deps/libuint-9ccc38015c3e65bf.rmeta --cap-lints allow 
-C link-arg=-s` (signal: 11, SIGSEGV: invalid memory reference)
```


Any idea where to go from here? I'm on a m1 macbook btw

**Comment by baedrik** [comment]
Assaf updated the optimizer to fix the problem in the original message for this issue.  Are you using enigmampc/secret-contract-optimizer:1.0.6  ?

**Comment by luca992** [comment]
Yup, using 1.0.6, I can make a new issue if you'd like @baedrik

**Comment by assafmo** [comment]
Hi, I'll take a look, somehow missed this issue 🙏

**Comment by assafmo** [comment]
@baedrik you might want to consider pinning dependencies if this is becoming a recurring issue

**Comment by luca992** [comment]
I've looked into it some more and pretty sure my issue is with running enigmampc/secret-contract-optimizer on an arm64 m1 mac. So, not sure if there's anything I can do about that.

Edit: had success using an arm compiled docker image https://gist.github.com/Xiphiar/d766338204b5588658fccfd8bc21f7cc

**Comment by assafmo** [comment]
`enigmampc/secret-contract-optimizer:1.0.7` should now work (added arm64 build).
