### ISSUE TITLE
When I run `cosm wasm` I get tons of `use of undeclared crate or module` errors and a failed build

### ISSUE THREAD

**Issue by ChristianOConnor** [baedrik/snip721-reference-impl#8]
I am following this tutorial https://www.youtube.com/watch?v=jRuSOos9ig4.

In the above tutorial, in the `contracts` directory of `https://github.com/floAr/FigmentLearn-FromZeroToYourFirstSecretNFT.git`, I run `cargo generate --git https://github.com/baedrik/snip721-reference-impl.git --name my-snip721` which worked after installing `cargo-generate` with the command `cargo install cargo-generate`.

The next step is to run `cargo wasm` which fails immediately a bunch of `use of undeclared crate or module` for packages like `slice` and `io`. I also get a lot of `not found in this scope` errors.

Are these problems happening because I'm on an m1 mac? How do I fix this and get `cargo wasm` to run?  

**Update**  
This does not appear to be an m1 mac problem. It fails on my Windows 10 build as well.  

Just to reiterate, I did the following commands once in the contracts directory of `https://github.com/floAr/FigmentLearn-FromZeroToYourFirstSecretNFT.git`:   
`cargo generate --git https://github.com/baedrik/snip721-reference-impl.git --name my-snip721`  
`cd my-snip721`  
`cargo wasm`  

When a ran `cargo wasm` on my m1 mac AND my Windows 10 build, I got an endless string of similar errors. They mostly all follow this format:  
```
error[E0433]: failed to resolve: use of undeclared crate or module `slice`
    --> /Users/<myusername>/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.4.3/src/lib.rs:1594:13
     |
1594 |             slice::from_raw_parts(src.as_ptr() as *const u64, src.len())
     |             ^^^^^ use of undeclared crate or module `slice`
```  

I also got a bunch of errors that followed this format.  
```
error[E0425]: cannot find function `copy_nonoverlapping` in this scope
    --> /Users/<myusername>/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.4.3/src/lib.rs:1950:13
     |
1950 |             copy_nonoverlapping(
     |             ^^^^^^^^^^^^^^^^^^^ not found in this scope
...
2301 |             unsafe_write_slice_native!(src, dst, u32);
     |             ----------------------------------------- in this macro invocation
     |
     = note: this error originates in the macro `unsafe_write_slice_native` (in Nightly builds, run with -Z macro-backtrace for more info)
```  

So what seems to be the problem? FYI, I'm using the terminal in visual studio code to run the commands. On my Windows build I ran these commands in the vscode bash terminal, powershell terminal, and cmd termial. They all produced the same errors

**Comment by baedrik** [comment]
Just copy-pasted your commands
```
cargo generate --git https://github.com/baedrik/snip721-reference-impl.git --name my-snip721
cd my-snip721
cargo wasm
```
and it built fine for me.  Maybe you are running an old version of rust?  I'd start over from the beginning with this doc in case there was a missed step https://docs.scrt.network/dev/secret-contracts.html#create-your-first-secret-contract
